# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm ci
        
      - name: Deploy
        run: npm run deploy

